server:
  project: '@TarsusWord/RecordServer -l java -t @tarsus/ms -h 127.0.0.1 -p 14004 -w 10'
  database:
    url: jdbc:mysql://127.0.0.1:3306/word_server?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    initSize: 1
    minIdle: 1
    maxActive: 10
    maxAwait: 20000
    TimeBetweenConnectErrorMillis: 2000
  aliases:
    publicPath: src.main.java
    struct: struct

